---
- name: Final Cleanup
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Purge named resources (containers, networks)
      ansible.builtin.include_role:
        name: postgres
        tasks_from: clean.yml
      vars:
        postgres_container_name: "postgres_molecule_{{ item }}"
        postgres_network: "postgres_net_{{ item }}"
        postgres_secret_db_password_name: "postgres_db_password_{{ item }}"
        postgres_volume_name: "postgres_data_{{ item }}"
      loop: "{{ groups['all'] | default(['localhost']) }}"
      ignore_errors: true # noqa ignore-errors
