---

- name: Cleanup for Molecule Postgres Tests
  hosts: all:!localhost
  gather_facts: false
  vars_files:
    - test_vars.yml

  tasks:
    - name: "Purge Molecule resources for each tested OS"
      ansible.builtin.include_role:
        name: postgres
        tasks_from: clean.yml
      vars:
        postgres_instance: "{{ test_postgres_instance }}"
        postgres_secret_name: "{{ test_postgres_secret_name }}"
        postgres_volume: "{{ test_postgres_volume }}"
        postgres_network: "{{ test_postgres_network }}"
        postgres_clean_network: "{{ test_postgres_purge_network }}"
        postgres_purge_data: "{{ test_postgres_purge_data }}"
