---
- name: Prepare Secrets for Postgres
  hosts: localhost
  gather_facts: false
  become: true

  tasks:
    - name: Create secrets directory inside container
      ansible.builtin.file:
        path: /run/secrets
        state: directory
        mode: '0755'

    - name: Inject dummy password secret
      ansible.builtin.copy:
        content: "testpassword123"
        dest: /run/secrets/postgres_db_password
        mode: '0644'
