namespace: addonol
name: ansible_infra
version: 1.0.0
authors:
  - "addonol"
description: >
  Standalone and modular infrastructure roles (PostgreSQL, RabbitMQ, CAS Mock)
  and Airflow 3 orchestration using Rootless Podman.
readme: README.md
license:
  - MIT
tags:
  - infrastructure
  - standalone
  - podman
  - rootless
  - airflow
  - postgres
  - rabbitmq
  - cas
  - sso
repository: "https://github.com/addonol/ansible-infra"
