---

idx: "{{ ansible_play_hosts_all.index(inventory_hostname) }}"

test_rabbitmq_image: "docker.io/library/rabbitmq:3.13-management-alpine"
test_rabbitmq_instance: "rabbitmq_molecule_{{ inventory_hostname }}"
test_rabbitmq_volume: "rabbitmq_molecule_data_{{ inventory_hostname }}"
test_rabbitmq_network: "infra_net_{{ inventory_hostname }}"
test_rabbitmq_secret_name: "rabbitmq_molecule_{{ inventory_hostname }}_password"
test_rabbitmq_user: "molecule_admin"
test_rabbitmq_pass: "testpassword123"
test_rabbitmq_management_port:  "{{ 5672 + idx | int }}"
test_rabbitmq_ui_port: "{{ 15672 + idx | int }}"
test_rabbitmq_purge_data: true
test_rabbitmq_purge_network: true
