---

# ==============================================================================
# 🗄️ DATABASE (Postgres Standalone)
# ==============================================================================
airflow_postgres_instance: "airflow_postgres"
airflow_postgres_db_name: "airflow_db"
airflow_postgres_db_user: "airflow_user"
airflow_postgres_db_pass: "{{ vault_postgres_password }}"
airflow_postgres_volume: "airflow_pg_data"
airflow_postgres_port: 5432


# ==============================================================================
# 🐰 BROKER (RabbitMQ Standalone)
# ==============================================================================
airflow_rabbitmq_instance: "airflow_rabbitmq"
airflow_rabbitmq_user: "mq_admin"
airflow_rabbitmq_pass: "{{ vault_rabbitmq_password }}"
airflow_rabbitmq_volume: "airflow_mq_data"
airflow_rabbitmq_management_port: 5672


# ==============================================================================
# 🌍 AIRFLOW
# ==============================================================================
airflow_common_executor: "CeleryExecutor"
airflow_common_load_examples: "false"
airflow_common_execution_api_url: "http://airflow_webserver_{{ inventory_hostname | default('prod') }}:8080/execution/"
airflow_common_network: "infra_net"
airflow_common_image: "docker.io/apache/airflow:3.1.7-python3.12"
airflow_common_webserver_port: 8080
airflow_common_purge_network: false
airflow_common_purge_data: false
airflow_common_project_root: "{{ playbook_dir }}/.."
airflow_common_dags_folder: "{{ airflow_common_project_root }}/airflow/dags"
airflow_common_logs_folder: "{{ airflow_common_project_root }}/airflow/logs"
airflow_common_config_dir: "{{ airflow_base_dir }}/config"
airflow_common_instance: "airflow"
airflow_common_admin_user: "admin"
airflow_common_admin_pass: "{{ vault_airflow_admin_password }}"
airflow_common_admin_email: "admin@example.com"
airflow_common_fernet_key: "{{ vault_airflow_fernet_key }}"
airflow_common_webserver_secret_key: "{{ vault_airflow_webserver_secret_key }}"
airflow_common_jwt_secret: "{{ vault_airflow_webserver_secret_key }}"
airflow_common_config: "airflow_config"
airflow_common_admin_pass_secret_name: "airflow_pass"
airflow_common_postgres_instance: "{{ airflow_postgres_instance }}"
airflow_common_postgres_db_user: "{{ airflow_postgres_db_user }}"
airflow_common_postgres_db_pass: "{{ airflow_postgres_db_pass }}"
airflow_common_postgres_db_name: "{{ airflow_postgres_db_name }}"
airflow_common_postgres_port: "{{ airflow_postgres_port }}"
airflow_common_rabbitmq_instance: "{{ airflow_rabbitmq_instance }}"
airflow_common_rabbitmq_user: "{{ airflow_rabbitmq_user }}"
airflow_common_rabbitmq_pass: "{{ airflow_rabbitmq_pass }}"
airflow_common_rabbitmq_management_port: "{{ airflow_rabbitmq_management_port }}"
