---
# ==============================================================================
# GLOBAL INFRASTRUCTURE SETTINGS
# ==============================================================================
airflow_network: "airflow_net"
airflow_image: "docker.io/apache/airflow:2.11.1-python3.12"
airflow_executor: "CeleryExecutor"

# Local paths for volume mounting
airflow_dags_folder: "{{ playbook_dir }}/../airflow/dags"

# ==============================================================================
# DATABASE SETTINGS (PostgreSQL)
# ==============================================================================

# Container configuration
postgres_container_name: "postgres"
postgres_image: "docker.io/library/postgres:16-alpine"
postgres_network: "postgres_network"

# Postgres Settings
postgres_db_name: "postgres_db"
postgres_db_user: "postgres_user"
postgres_db_password: "{{ vault_postgres_password }}"

# The secret name in Podman
postgres_secret_db_password_name: "postgres_db_password"

# Ports
postgres_port_number: 5432

# Persistence
postgres_volume_name: "postgres_data"


# ==============================================================================
# BROKER SETTINGS (RabbitMQ)
# ==============================================================================

# Container configuration
rabbitmq_container_name: "rabbitmq_broker"
rabbitmq_image: "docker.io/library/rabbitmq:3.13-management-alpine"
rabbitmq_network: "rabbitmq_net"

# RabbitMQ Settings
rabbitmq_user: "mq_admin"

# The secret name in Podman
rabbitmq_secret_pass_name: "rabbitmq_password"

# Ports (Management UI & AMQP)
rabbitmq_management_port: 5672
rabbitmq_ui_port: 15672

# Persistence
rabbitmq_volume_name: "rabbitmq_data"

# ==============================================================================
# AIRFLOW CORE COMPONENTS
# ==============================================================================

# Scheduler
airflow_scheduler_container_name: "airflow_scheduler"

# Worker
airflow_worker_container_name: "airflow_worker"

# Triggerer
airflow_triggerer_container_name: "airflow_triggerer"

# Webserver
airflow_webserver_container_name: "airflow_webserver"
airflow_webserver_port: 8080
airflow_webserver_secret_key: "{{ vault_airflow_webserver_secret_key }}"

# ==============================================================================
# AIRFLOW APPLICATION SETTINGS (RBAC & Admin)
# ==============================================================================
airflow_admin_user: "admin"
airflow_admin_firstname: "Admin"
airflow_admin_lastname: "User"
airflow_admin_email: "admin@example.com"
airflow_admin_password: "{{ vault_airflow_admin_password }}"
