---
- name: Remove RabbitMQ container
  containers.podman.podman_container:
    name: "{{ rabbitmq_container_name }}"
    state: absent
  delegate_to: "{{ (molecule_yml is defined) | ternary('localhost', inventory_hostname) }}"

- name: Remove RabbitMQ secret
  containers.podman.podman_secret:
    name: "{{ rabbitmq_secret_pass_name }}"
    state: absent
  delegate_to: "{{ (molecule_yml is defined) | ternary('localhost', inventory_hostname) }}"

- name: Remove RabbitMQ volume
  containers.podman.podman_volume:
    name: "{{ rabbitmq_volume_name }}"
    state: absent
  delegate_to: "{{ (molecule_yml is defined) | ternary('localhost', inventory_hostname) }}"

- name: Remove RabbitMQ network
  containers.podman.podman_network:
    name: "{{ rabbitmq_network }}"
    state: absent
  delegate_to: "{{ (molecule_yml is defined) | ternary('localhost', inventory_hostname) }}"

- name: Remove temporary configuration file from host
  ansible.builtin.file:
    path: "/tmp/rabbitmq_{{ rabbitmq_container_name }}.conf"
    state: absent
  delegate_to: "{{ (molecule_yml is defined) | ternary('localhost', inventory_hostname) }}"
