---
- name: Ensure podman network exists
  containers.podman.podman_network:
    name: "{{ rabbitmq_network | default('rabbitmq_net') }}"
    state: present
  delegate_to: "{{ (molecule_yml is defined) | ternary('localhost', inventory_hostname) }}"

- name: Create Podman secret for RabbitMQ password
  containers.podman.podman_secret:
    name: "{{ rabbitmq_secret_pass_name | default('rabbitmq_password') }}"
    data: "{{ vault_rabbitmq_password }}"
    state: present
  no_log: true
  delegate_to: "{{ (molecule_yml is defined) | ternary('localhost', inventory_hostname) }}"

- name: Create RabbitMQ configuration from template
  ansible.builtin.template:
    src: rabbitmq.conf.j2
    dest: "/tmp/rabbitmq_{{ rabbitmq_container_name }}.conf"
    mode: '0644'
  delegate_to: "{{ (molecule_yml is defined) | ternary('localhost', inventory_hostname) }}"

- name: Launch RabbitMQ container
  containers.podman.podman_container:
    name: "{{ rabbitmq_container_name }}"
    image: "{{ rabbitmq_image | default('docker.io/library/rabbitmq:3-management-alpine') }}"
    state: started
    restart_policy: always
    network: "{{ rabbitmq_network | default('rabbitmq_net') }}"
    secrets:
      - "{{ rabbitmq_secret_pass_name | default('rabbitmq_password') }}"
    env:
      RABBITMQ_CONFIG_FILE: "/etc/rabbitmq/rabbitmq.conf"
    ports:
      - "{{ rabbitmq_management_port | default('5672') }}:5672"
      - "{{ rabbitmq_ui_port | default('15672') }}:15672"
    volumes:
      - "/tmp/rabbitmq_{{ rabbitmq_container_name }}.conf:/etc/rabbitmq/rabbitmq.conf:Z"
      - "{{ rabbitmq_volume_name | default('rabbitmq_data') }}:/var/lib/rabbitmq:Z"
  delegate_to: "{{ (molecule_yml is defined) | ternary('localhost', inventory_hostname) }}"
