---
- name: Ensure podman network exists
  containers.podman.podman_network:
    name: "{{ airflow_network }}"
    state: present

- name: Create temporary RabbitMQ config from template
  ansible.builtin.template:
    src: rabbitmq.conf.j2
    dest: "/tmp/rabbitmq_bootstrap.conf"
    mode: '0600'
  no_log: true

- name: Create Podman secret for RabbitMQ password
  containers.podman.podman_secret:
    name: mq_password
    data: "{{ rabbitmq_password }}"
    state: present
  no_log: true

- name: Launch RabbitMQ container
  containers.podman.podman_container:
    name: "{{ rabbitmq_container_name }}"
    image: "docker.io/library/rabbitmq:3-management-alpine"
    state: started
    restart_policy: always
    network: "{{ airflow_network }}"
    userns: keep-id
    secrets:
      - mq_password
    env:
      RABBITMQ_CONFIG_FILE: "/etc/rabbitmq/rabbitmq.conf"
    ports:
      - "{{ rabbitmq_amqp_port }}:5672"
      - "{{ rabbitmq_management_port }}:15672"
    volume:
      - "/tmp/rabbitmq_bootstrap.conf:/etc/rabbitmq/rabbitmq.conf:Z"
      - "rabbitmq_data:/var/lib/rabbitmq:Z"
