---

- name: Set deployment facts
  ansible.builtin.set_fact:
    rabbitmq_delegate_host: "{{ (molecule_yml is defined) | ternary('localhost', inventory_hostname) }}"

- name: "Health Check - Wait for readiness {{ rabbitmq_instance }}"
  ansible.builtin.command: >
    podman inspect --format '{{ '{{' }} .State.Health.Status {{ '}}' }}' {{ rabbitmq_instance }}
  register: rabbitmq_health
  until: "'healthy' in rabbitmq_health.stdout"
  retries: 60
  delay: 5
  changed_when: false
  delegate_to: "{{ rabbitmq_delegate_host }}"

- name: "Security Check - Inspect for leaks {{ rabbitmq_instance }}"
  ansible.builtin.command: "podman inspect {{ rabbitmq_instance }}"
  register: rabbitmq_inspect
  changed_when: false
  delegate_to: "{{ rabbitmq_delegate_host }}"

- name: "Assert Security & Readiness {{ rabbitmq_instance }}"
  ansible.builtin.assert:
    that:
      - "'healthy' in rabbitmq_health.stdout"
      - "rabbitmq_pass not in rabbitmq_inspect.stdout"
    fail_msg: "SECURITY ALERT: Secret leak or Broker unhealthy for {{ rabbitmq_instance }}!"
    success_msg: "SUCCESS: {{ rabbitmq_instance }} is healthy and secure."
