---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: podman

platforms:
  - name: molecule-debian12
    image: docker.io/geerlingguy/docker-debian12-ansible:latest
    pre_build_image: true
    delete_volumes: true

  - name: molecule-ubuntu2204
    image: docker.io/geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    delete_volumes: true

  - name: molecule-fedora39
    image: docker.io/geerlingguy/docker-fedora39-ansible:latest
    pre_build_image: true
    delete_volumes: true

  - name: molecule-rocky9
    image: docker.io/geerlingguy/docker-rockylinux9-ansible:latest
    pre_build_image: true
    delete_volumes: true

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      stdout_callback: ansible.builtin.default
      result_format: yaml
      roles_path: ../../../roles
      display_skipped_hosts: false
      display_ok_hosts: true
      deprecation_warnings: false
      action_warnings: false
      verbosity: 0
    ssh_connection:
      pipelining: true

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
