---
rabbitmq_instance: "standalone_rabbitmq"
rabbitmq_image: "docker.io/library/rabbitmq:3.13-management-alpine"
rabbitmq_volume: "rabbitmq_data"
rabbitmq_network: "rabbitmq_network"
rabbitmq_secret_name: "rabbitmq_password"
rabbitmq_user: "rabbitmq_user"
rabbitmq_pass: "changeme"
rabbitmq_management_port: 5672
rabbitmq_ui_port: 15672
rabbitmq_purge_data: false
rabbitmq_purge_network: false
