---
- name: Launch Airflow Webserver container
  containers.podman.podman_container:
    name: "{{ airflow_webserver_container_name }}"
    image: "{{ airflow_image }}"
    state: started
    restart_policy: always
    network: "{{ airflow_network }}"
    command: webserver
    ports:
      - "{{ airflow_webserver_port }}:8080"
    secrets:
      - airflow_fernet_key
      - airflow_db_conn
    env:
      AIRFLOW_CONFIG: "/opt/airflow/airflow.cfg"
    volume:
      - "/tmp/airflow_bootstrap.cfg:/opt/airflow/airflow.cfg:Z"
      - "{{ airflow_dags_folder }}:/opt/airflow/dags:Z"
      - "airflow_logs:/opt/airflow/logs:Z"
