---
galaxy_info:
  author: addonol
  description: Deploy and manage Airflow Triggerer (AsyncIO) on Podman Rootless.
  company: none
  license: MIT
  min_ansible_version: "2.12"
  galaxy_tags:
    - airflow
    - podman
    - triggerer
    - asyncio
    - deferrable
dependencies: []
