---
postgres_image: "docker.io/library/postgres:16-alpine"
postgres_secret_db_password_name: "postgres_db_password"
postgres_db_name: "postgres_db"
postgres_db_user: "postgres_user"
postgres_container_name: "postgres"
postgres_network: "postgres_net"
postgres_port_number: 5432
postgres_volume_name: "postgres_data"
