---

- name: Set deployment facts
  ansible.builtin.set_fact:
    postgres_delegate_host: "{{ (molecule_yml is defined) | ternary('localhost', inventory_hostname) }}"

- name: "Ensure network exists: {{ postgres_network }}"
  containers.podman.podman_network:
    name: "{{ postgres_network }}"
    state: present
  delegate_to: "{{ postgres_delegate_host }}"

- name: "Create secret for instance: {{ postgres_instance }}"
  containers.podman.podman_secret:
    name: "{{ postgres_secret_name }}"
    data: "{{ postgres_db_pass }}"
    state: present
  no_log: true
  delegate_to: "{{ postgres_delegate_host }}"

- name: "Launch Postgres container: {{ postgres_instance }}"
  containers.podman.podman_container:
    name: "{{ postgres_instance }}"
    image: "{{ postgres_image }}"
    state: started
    restart_policy: always
    network: "{{ postgres_network }}"
    secrets:
      - "{{ postgres_secret_name }}"
    env:
      POSTGRES_DB: "{{ postgres_db_name }}"
      POSTGRES_USER: "{{ postgres_db_user }}"
      POSTGRES_PASSWORD_FILE: "/run/secrets/{{ postgres_secret_name }}"
    volumes:
      - "{{ postgres_volume }}:/var/lib/postgresql/data:Z"
    ports:
      - "{{ postgres_port }}:5432"
    health_cmd: "/usr/local/bin/pg_isready -U {{ postgres_db_user }} -d {{ postgres_db_name }}"
    health_interval: "5s"
    health_retries: 5
    health_start_period: "10s"
    health_timeout: "5s"
  delegate_to: "{{ postgres_delegate_host }}"
