---

- name: Set deployment facts
  ansible.builtin.set_fact:
    postgres_delegate_host: "{{ (molecule_yml is defined) | ternary('localhost', inventory_hostname) }}"

- name: "Health Check - Wait for readiness of {{ postgres_instance }}"
  ansible.builtin.command: >
    podman inspect --format '{{ '{{' }} .State.Health.Status {{ '}}' }}' {{ postgres_instance }}
  register: postgres_container_health
  until: "'healthy' in postgres_container_health.stdout"
  retries: 15
  delay: 2
  changed_when: false
  delegate_to: "{{ postgres_delegate_host }}"

- name: "Security Check - Inspect metadata for leaks {{ postgres_instance }}"
  ansible.builtin.command: "podman inspect {{ postgres_instance }}"
  register: postgres_db_inspect
  changed_when: false
  delegate_to: "{{ postgres_delegate_host }}"

- name: "Assert Security & Readiness {{ postgres_instance }}"
  ansible.builtin.assert:
    that:
      - "postgres_container_health.stdout == 'healthy'"
      - "postgres_db_pass not in postgres_db_inspect.stdout"
    fail_msg: "ERROR: {{ postgres_instance }} failed health or security check!"
    success_msg: "SUCCESS: {{ postgres_instance }} is healthy and secure."
  delegate_to: "{{ postgres_delegate_host }}"
