---

- name: Deployment - Standalone RabbitMQ Broker
  hosts: all
  gather_facts: false

  tasks:
    - name: Orchestrating RabbitMQ Instance
      block:
        - name: Execute Deployment
          ansible.builtin.include_role:
            name: rabbitmq
            tasks_from: main.yml

        - name: Execute Validation
          ansible.builtin.include_role:
            name: rabbitmq
            tasks_from: verify.yml

      rescue:
        - name: "🚨 FAILURE DETECTED - Rolling back"
          ansible.builtin.include_role:
            name: rabbitmq
            tasks_from: clean.yml
          vars:
            rabbitmq_purge_data: false
