---

- name: Deploy a Standalone Postgres Instance
  hosts: all
  gather_facts: false

  tasks:
    - name: "Orchestrating Standalone Database"
      block:
        - name: Run Postgres Role
          ansible.builtin.include_role:
            name: postgres
            tasks_from: main.yml

        - name: Verify Health and Security
          ansible.builtin.include_role:
            name: postgres
            tasks_from: verify.yml

      rescue:
        - name: 🚨 Cleanup on Failure
          ansible.builtin.include_role:
            name: postgres
            tasks_from: clean.yml
          vars:
            postgres_purge_data: false
