---
- name: Deployment - RabbitMQ broker Role
  hosts: all
  gather_facts: false

  tasks:
    - name: RabbitMQ broker Deployment Phase
      block:
        - name: Deploy Role
          ansible.builtin.include_role:
            name: rabbitmq
            tasks_from: main.yml

        - name: Verify RabbitMQ broker
          ansible.builtin.include_role:
            name: rabbitmq
            tasks_from: verify.yml

      rescue:
        - name: 🚨 FAILURE DETECTED - Purging Resources
          ansible.builtin.include_role:
            name: rabbitmq
            tasks_from: clean.yml
